project:
  type: book
  output-dir: docs

book:
  title: "Salmon Habitat Mapping in the Central Kenai Peninsula 2021-2025 [DRAFT]"
  author: "Benjamin Meyer, Kenai Watershed Forum"
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd
    - discussion.qmd
    - future_directions.qmd
    - references.qmd

repo-url: https://github.com/Kenai-Watershed-Forum/salmon-habitat-mapping
repo-actions: [edit]
search: true
downloads: [docx]

bibliography: references.bib

format:
  html:
    theme: cosmo
  docx:
    toc: true
    toc-depth: 2
    toc-title: "Table of contents"
    number-sections: true

editor: visual
